# Generated by Django 2.1.2 on 2019-01-04 07:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0002_remove_chat_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='send_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发送时间'),
        ),
    ]
